// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu4tCf4BQhJ2Q7RRfuJGVHcxLcZm4QX6I',
    appId: '1:281402735455:web:87aa38ca0fd579f9d4d4ea',
    messagingSenderId: '281402735455',
    projectId: 'fitcoach-project',
    authDomain: 'fitcoach-project.firebaseapp.com',
    storageBucket: 'fitcoach-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAshB3BYbrcpc5S7Txbhz86pwZUPtdqJlQ',
    appId: '1:281402735455:android:326697276461bf21d4d4ea',
    messagingSenderId: '281402735455',
    projectId: 'fitcoach-project',
    storageBucket: 'fitcoach-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9GCWdGJodCO3p97t79yfX4vxRGjvKYew',
    appId: '1:281402735455:ios:35877fa4f6da85f5d4d4ea',
    messagingSenderId: '281402735455',
    projectId: 'fitcoach-project',
    storageBucket: 'fitcoach-project.firebasestorage.app',
    iosBundleId: 'com.example.fitcoach',
  );
}
